# Generated by Django 3.0.8 on 2020-07-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200708_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
