# Generated by Django 3.0.8 on 2020-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default='名無しさん', max_length=255, verbose_name='ニックネーム'),
        ),
    ]
