# Generated by Django 3.0.8 on 2020-07-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200709_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
