# Generated by Django 3.0.8 on 2020-07-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200710_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Blog', verbose_name='対象記事'),
        ),
    ]
